exclude:
    (?x)^(
        lib/|
        notebooks/|
        tests/|
        devops_pipelines/|
        docs/
    )

repos:
-  repo: https://github.com/pre-commit/pre-commit-hooks
   rev: "v3.4.0"
   hooks:
   -  id: check-merge-conflict
   -  id: check-yaml

-   repo: https://github.com/python-poetry/poetry
    rev: "2.1.3"
    hooks:
    -   id: poetry-check
    -   id: poetry-lock

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
    -   id: mypy
        args: [--config-file=./pyproject.toml]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
    -   id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [--config=./pyproject.toml]
    -   id: ruff-format
        types_or: [ python, pyi, jupyter ]
        args: [--config=./pyproject.toml]
