$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: test_gh_pages-aml-environment
image: mcr.microsoft.com/azureml/openmpi5.0-ubuntu24.04
conda_file: conda.yml
description: Environment created from a Docker image plus Conda environment.